language: shell
sudo: required
dist: trusty
services:
  - docker

git:
  depth: 2
  submodules: false

matrix:
  fast_finish: true
  include:
    - env: IMAGE=dist-i386-netbsd DEPLOY=1
      if: branch = netbsd-i386-build

before_install:
  - zcat $HOME/docker/rust-ci.tar.gz | docker load || true
  - mkdir -p $HOME/rustsrc
  # FIXME(#46924): these two commands are required to enable IPv6,
  # they shouldn't exist, please revert once more official solutions appeared.
  # see https://github.com/travis-ci/travis-ci/issues/8891#issuecomment-353403729
  - if [ "$TRAVIS_OS_NAME" = linux ]; then
      echo '{"ipv6":true,"fixed-cidr-v6":"fd9a:8454:6789:13f7::/64"}' | sudo tee /etc/docker/daemon.json;
      sudo service docker restart;
    fi

install:
  - case "$TRAVIS_OS_NAME" in
        linux)
          travis_retry curl -fo $HOME/stamp https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rust-ci-mirror/2017-03-17-stamp-x86_64-unknown-linux-musl &&
            chmod +x $HOME/stamp &&
            export PATH=$PATH:$HOME
          ;;
        osx)
          if [[ "$RUST_CHECK_TARGET" == dist ]]; then
            travis_retry brew update &&
            travis_retry brew install xz;
          fi &&
          travis_retry curl -fo /usr/local/bin/sccache https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rust-ci-mirror/2017-05-12-sccache-x86_64-apple-darwin &&
            chmod +x /usr/local/bin/sccache &&
          travis_retry curl -fo /usr/local/bin/stamp https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rust-ci-mirror/2017-03-17-stamp-x86_64-apple-darwin &&
            chmod +x /usr/local/bin/stamp
          ;;
    esac

before_script:
  - >
      echo "#### Disk usage before running script:";
      df -h;
      du . | sort -nr | head -n100
  - >
      RUN_SCRIPT="src/ci/init_repo.sh . $HOME/rustsrc";
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
          export RUN_SCRIPT="$RUN_SCRIPT && src/ci/run.sh";
      else
          export RUN_SCRIPT="$RUN_SCRIPT && src/ci/docker/run.sh $IMAGE";
      fi

# Log time information from this machine and an external machine for insight into possible
# clock drift. Timezones don't matter since relative deltas give all the necessary info.
script:
  - >
      date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
  - stamp sh -x -c "$RUN_SCRIPT"
  - >
      date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)

after_success:
  - >
      echo "#### Build successful; Disk usage after running script:";
      df -h;
      du . | sort -nr | head -n100

after_failure:
  - >
      echo "#### Build failed; Disk usage after running script:";
      df -h;
      du . | sort -nr | head -n100

  # One of these is the linux sccache log, one is the OSX sccache log. Instead
  # of worrying about what system we are just cat both. One of these commands
  # will fail but that's ok, they'll both get executed.
  - cat obj/tmp/sccache.log
  - cat /tmp/sccache.log

  # Random attempt at debugging currently. Just poking around in here to see if
  # anything shows up.
  - ls -lat $HOME/Library/Logs/DiagnosticReports/
  - find $HOME/Library/Logs/DiagnosticReports
      -type f
      -not -name '*.stage2-*.crash'
      -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash'
      -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \;
      -exec head -750 {} \;
      -exec echo travis_fold":"end:crashlog \;

  # attempt to debug anything killed by the oom killer on linux, just to see if
  # it happened
  - dmesg | grep -i kill

# Save tagged docker images we created and load them if they're available
# Travis saves caches whether the build failed or not, nuke rustsrc if
# the failure was while updating it (as it may be in a bad state)
# https://github.com/travis-ci/travis-ci/issues/4472
before_cache:
  - docker history -q rust-ci |
    grep -v missing |
    xargs docker save |
    gzip > $HOME/docker/rust-ci.tar.gz

notifications:
  email: false

cache:
  directories:
    - $HOME/docker

before_deploy:
  - mkdir -p deploy/$TRAVIS_COMMIT
  - >
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          rm -rf build/dist/doc &&
          cp -r build/dist/* deploy/$TRAVIS_COMMIT;
      else
          rm -rf obj/build/dist/doc &&
          cp -r obj/build/dist/* deploy/$TRAVIS_COMMIT;
      fi
  - travis_retry gem update --system
  - ls -la deploy/$TRAVIS_COMMIT

deploy:
  provider: releases
  api_key:
    secure: YetgCYGfZxSWFULNzEPpXLP6f3C0W4OIw1kn8Xus/+1caJMVSUOBQxyZBXT/tjToqMbmVgglrjwoXQweHYCPq0UAGbugkH6xoEWf2f86rlYnH172x3ymPPTZ7AcUqM4ve5qsfVI8xYbmqmNUOFQYvqF1kYMNvPxQIxOO7qlMO5JfG1RMzVZKzKQ6bBDA1DO9kpTpEgcQwxffrvZzTRpfQ1xBfggM4yTfDVSTH+lIreYPEDPfZMKJmo9FDpmVhcein1coRSo8MGcLntn8rf05UgTHb5hemWvYbQW/dOhvKMihYp8yOdu3s0q5cVLpITpayFa8choHm67x9ET7Jr+5jTv0RcUh4flYkhCYPeKtx+k3IQUACTjtLgqWXCP98EfmHCBxIECCQnRjv6S3wqAw0rDX9qY7lNljW00MxL+cZ1cql+nijUs9fqIXWPxvyihI0/IFJkK61/xik25tcwkzxpw6FTdffWc/WKvpUl0zlzKqsN+ui+mNxzyJqLbfmrBe80kqLicUHaWFtOsIH3826XPfXU1AO1FSA2CVC55uR/T/FnL26Na97px0J2uECz5o44nwmf73mtvnnbx80qd6sNV8BzNgFMbHI7YfrkHLplIjcz3VjMXl7dnlyaNhl4xVL40r5k5bs9qeU6cvNVe/VPw1jwpJO5NWD9xowAeVL2U=
  file_glob: true
  file: deploy/$TRAVIS_COMMIT/*
  on:
    repo: iquiw/rust
    tags: true
